package com.weather.openweather.unittest

object SearchUtil {

    private val existingCitiesList = arrayOf(
        "New York",
        "Chicago",
        "Boston",
        "San Diego",
        "Los Angeles",
        "San Francisco",
        "Philadelphia",
        "Austin",
        "Seattle",
        "Nashville",
        "Phoenix",
        "San Jose",
        "San Antonio",
        "Oklahoma City",
        "Las Vegas",
        "Baltimore",
        "Houston",
        "New Orleans",
        "Washington",
        "Washington, D.C.",
        "Columbus",
        "Dallas",
        "Indianapolis",
        "Atlanta",
        "Detroit",
        "Denver",
        "Honolulu",
        "Jacksonville",
        "Fort Worth",
        "El Paso",
        "Kansas City",
        "Milwaukee",
        "Memphis",
        "Sacramento",
        "Charlotte",
        "Portland",
        "Fresno",
        "Raleigh",
        "Albuquerque",
        "Tucson",
        "Colorado Springs",
        "Louisville",
        "Miami",
        "Tulsa",
        "Wichita",
        "Omaha",
        "Virginia Beach",
        "Salt Lake City",
        "Oakland",
        "Des Moines",
        "Charleston",
        "Mesa",
        "California",
        "Texas",
        "Florida",
        "Indiana",
        "Michigan",
        "Missouri",
        "New Jersey",
        "St. Petersburg",
        "Moreno Valley",
        "Tacoma",
        "Rochester",
        "Columbus",
        "Frisco",
        "Oxnard",
        "Sioux Falls",
        "Tallahassee",
        "Virginia",
        "Louisiana",
        "Illinois",
        "Aurora",
        "Santa Rosa",
        "Lancaster",
        "Springfield",
        "Hayward",
        "Clarksville",
        "Paterson",
        "Hollywood",
        "Mississippi",
        "Rockford",
        "Fullerton",
        "West Valley City",
        "Elizabeth",
        "Kent",
        "Miramar",
        "Midland",
        "Iowa",
        "Carrollton",
        "Fargo",
        "Pearland",
        "North Dakota",
        "Thousand Oaks",
        "Allentown",
        "Colorado",
        "Clovis",
        "Hartford",
        "Connecticut",
        "Wilmington",
        "Fairfield",
        "Cambridge",
        "Billings",
        "West Palm Beach",
        "Westminster",
        "Provo",
        "Lewisville",
        "New Mexico",
        "Odessa",
        "Nevada",
        "Greeley",
        "Tyler",
        "Oregon",
        "Rio Rancho",
        "Massachusetts",
        "New Bedford",
        "Longmont",
        "Hesperia",
        "Chico",
        "Burbank",
        "Murfreesboro",
        "Kansas",
        "Idaho",
        "Pittsburgh",
        "Detroit",
        "Pennsylvania",
        "Jacksonville",
        "Indianapolis",
        "Charlotte",
        "Jefferson City"
    )
    fun validCityNameInput(
        cityName : String) : Boolean {
        // write conditions along with their return statement
        // if cityname is empty return false
        if (cityName.isEmpty()){
            return false
        }
        // if cityname exists in the existingcities list return false
        if (cityName in existingCitiesList){
            return false
        }
        // if char count of the cityname is less than 3 return false
        if (cityName.count { it.isLetter() } < 3){
            return false
        }
        return true
    }
}